# Generated by Django 5.2.3 on 2025-08-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseAssignment",
            new_name="Assignment",
        ),
        migrations.RenameModel(
            old_name="ModuleLesson",
            new_name="Lesson",
        ),
        migrations.RenameModel(
            old_name="CourseModule",
            new_name="Module",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="module",
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to="elearning_app.assignment",
            ),
            preserve_default=False,
        ),
    ]
