# Generated by Django 5.2.3 on 2025-08-13 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0002_rename_courseassignment_assignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="grade",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
