# Generated by Django 5.2.3 on 2025-08-19 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0003_alter_assignmentsubmission_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_updates",
                to="elearning_app.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statusupdate",
            name="course_progress",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
            preserve_default=False,
        ),
    ]
