# Generated by Django 5.2.3 on 2025-08-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0004_statusupdate_course_statusupdate_course_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
