# Generated by Django 5.2.3 on 2025-08-19 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0005_chat_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatparticipant",
            name="chat_muted",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="weight",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="review",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="canceled_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="final_grade",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
