# Generated by Django 5.2.3 on 2025-08-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0006_remove_chatparticipant_chat_muted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
