# Generated by Django 5.2.3 on 2025-08-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elearning_app",
            "0008_remove_course_estimated_duration_course_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="feedback",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
