# Generated by Django 5.2.3 on 2025-08-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0009_assignmentsubmission_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_order",
        ),
    ]
