# Generated by Django 5.2.3 on 2025-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0010_remove_lesson_lesson_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.CharField(default="-", max_length=1000),
            preserve_default=False,
        ),
    ]
