# Generated by Django 5.2.3 on 2025-08-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0011_alter_assignment_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                    ("Removed", "Removed"),
                ],
                default="Active",
                max_length=9,
            ),
        ),
    ]
