# Generated by Django 5.2.3 on 2025-08-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "elearning_app",
            "0014_alter_course_taught_by_alter_userblocks_blocked_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserBlocks",
            new_name="UserBlock",
        ),
    ]
