# Generated by Django 5.2.3 on 2025-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning_app", "0015_rename_userblocks_userblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="removed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
